name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: cinnamon-profile-manager-linux-x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x.x

      - name: Install dependencies
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y zip unzip dconf-cli
          fi
        shell: bash

      - name: Compile binary
        run: |
          deno compile --target ${{ matrix.target }} --allow-env=TF_BUILD,TERM,CI,TEAMCITY_VERSION,COLORTERM,COLOR,ANSI_COLORS,BEARZ_ANSI_COLOR,CLICOLOR_FORCE,CINNAMON_PROFILES_DIR,DCONF_SETTINGS_FILE,HOME --allow-sys=osRelease --allow-read --allow-write --allow-run=cp,rm,which,zip,unzip,dconf --output ${{ matrix.asset_name }} main.ts
      
      - name: Check binary exists
        run: |
          ls -la ${{ matrix.asset_name }}
          echo "Binary compiled successfully"
